import { LangCode } from './lang-codes'

export const langCodeToNativeLanguageNameMap: Record<LangCode, string> = {
  [LangCode.ENGLISH]: 'English',
  [LangCode.SPANISH]: 'español',
  [LangCode.GERMAN]: 'deutsch',
  [LangCode.FRENCH]: 'français',
  [LangCode.ITALIAN]: 'italiano',
  [LangCode.POLISH]: 'polski',
  [LangCode.CZECH]: 'čeština',
  [LangCode.UKRAINIAN]: 'українська',
  [LangCode.RUSSIAN]: 'русский',
  [LangCode.PORTUGUESE]: 'português',
  [LangCode.VIETNAMESE]: 'tiếng Việt',
  [LangCode.CHINESE]: '中文',
  [LangCode.HINDI]: 'हिन्दी',
  [LangCode.INDONESIAN]: 'Bahasa Indonesia',
  [LangCode.MALAY]: 'Bahasa Melayu',
  [LangCode.JAPANESE]: '日本語',
  [LangCode.KOREAN]: '한국어',
  [LangCode.TAMIL]: 'தமிழ்',
  [LangCode.TURKISH]: 'Türkçe',
  [LangCode.ROMANIAN]: 'Română',
  [LangCode.SWEDISH]: 'svenska',
  [LangCode.NORWEGIAN]: 'norsk',
  [LangCode.DANISH]: 'dansk',
  [LangCode.SLOVAK]: 'slovenčina',
  [LangCode.DUTCH]: 'Nederlands',
  [LangCode.THAI]: 'ไทย',
  [LangCode.HUNGARIAN]: 'magyar',
  [LangCode.GREEK]: 'ελληνικά',
  [LangCode.FINNISH]: 'suomi',
  [LangCode.BULGARIAN]: 'български',
  [LangCode.CATALAN]: 'català',
}

export const langCodeToNativeLatinLanguageNameMap: Record<LangCode, string> = {
  [LangCode.ENGLISH]: 'English',
  [LangCode.SPANISH]: 'espanol',
  [LangCode.GERMAN]: 'deutsch',
  [LangCode.FRENCH]: 'francais',
  [LangCode.ITALIAN]: 'italiano',
  [LangCode.POLISH]: 'polski',
  [LangCode.CZECH]: 'cestina',
  [LangCode.UKRAINIAN]: 'ukrainska',
  [LangCode.RUSSIAN]: 'russkiy',
  [LangCode.PORTUGUESE]: 'portugues',
  [LangCode.VIETNAMESE]: 'tieng viet',
  [LangCode.CHINESE]: 'zhong wen',
  [LangCode.HINDI]: 'hindi',
  [LangCode.INDONESIAN]: 'Bahasa Indonesia',
  [LangCode.MALAY]: 'Bahasa Melayu',
  [LangCode.JAPANESE]: 'nihongo',
  [LangCode.KOREAN]: 'Hangugeo',
  [LangCode.TAMIL]: 'tamil',
  [LangCode.TURKISH]: 'turkce',
  [LangCode.ROMANIAN]: 'romana',
  [LangCode.SWEDISH]: 'svenska',
  [LangCode.NORWEGIAN]: 'norsk',
  [LangCode.DANISH]: 'dansk',
  [LangCode.SLOVAK]: 'slovencina',
  [LangCode.DUTCH]: 'Nederlands',
  [LangCode.THAI]: 'thiy',
  [LangCode.HUNGARIAN]: 'magyar',
  [LangCode.GREEK]: 'ellinika',
  [LangCode.FINNISH]: 'suomi',
  [LangCode.BULGARIAN]: 'bulgarski',
  [LangCode.CATALAN]: 'catala',
}
