import {
  Brain,
  Briefcase,
  Camera,
  ChefHat,
  Clapperboard,
  Dumbbell,
  Gamepad2,
  GraduationCap,
  HandshakeIcon,
  Heart,
  History,
  Home,
  LucideIcon,
  MapPin,
  MessageCircle,
  Mic2,
  Music2,
  Newspaper,
  Palette,
  PiggyBank,
  ShoppingBag,
  Sun,
  Syringe,
  Tv,
  Users2,
  Mail,
} from 'lucide-react'
import { Topic } from '@yourbestaccent/core/constants/topics.ts'

type TopicIcon = {
  type: 'lucide' | 'emoji'
  icon: LucideIcon | string
}

export const TOPIC_TO_ICONS_MAP: Record<Topic, TopicIcon> = {
  greetings: { type: 'lucide', icon: HandshakeIcon },
  intro: { type: 'lucide', icon: Users2 },
  numbers: { type: 'emoji', icon: '➊' },
  family: { type: 'emoji', icon: '⚭' },
  food: { type: 'lucide', icon: ChefHat },
  directions: { type: 'lucide', icon: MapPin },
  shopping: { type: 'lucide', icon: ShoppingBag },
  travel: { type: 'lucide', icon: Home },
  medicine: { type: 'lucide', icon: Syringe },
  weather: { type: 'lucide', icon: Sun },
  business: { type: 'lucide', icon: Briefcase },
  letters: { type: 'lucide', icon: Mail },
  chatting: { type: 'lucide', icon: MessageCircle },
  slang: { type: 'lucide', icon: Mic2 },
  news: { type: 'lucide', icon: Newspaper },
  academia: { type: 'lucide', icon: GraduationCap },
  tech: { type: 'lucide', icon: Brain },
  art: { type: 'lucide', icon: Palette },
  history: { type: 'lucide', icon: History },
  socializing: { type: 'lucide', icon: Users2 },
  music: { type: 'lucide', icon: Music2 },
  emotions: { type: 'lucide', icon: Heart },
  nature: { type: 'emoji', icon: '❀' },
  career: { type: 'lucide', icon: Briefcase },
  interview: { type: 'lucide', icon: Users2 },
  cooking: { type: 'lucide', icon: ChefHat },
  gaming: { type: 'lucide', icon: Gamepad2 },
  sports: { type: 'lucide', icon: Dumbbell },
  finance: { type: 'lucide', icon: PiggyBank },
  cinema: { type: 'lucide', icon: Clapperboard },
  dancing: { type: 'lucide', icon: Music2 },
  socialMedia: { type: 'lucide', icon: Tv },
  gardening: { type: 'emoji', icon: '✿' },
  photography: { type: 'lucide', icon: Camera },
  fashion: { type: 'lucide', icon: ShoppingBag },
}
