packages:
  - apps/*
  - packages/*

catalog:
  '@ai-sdk/anthropic': 2.0.44
  '@anthropic-ai/sdk': 0.64.0
  '@babel/plugin-transform-react-jsx': 7.27.1
  '@expo/metro-runtime': 6.1.2
  '@expo/vector-icons': 15.0.3
  '@formatjs/intl-locale': 4.2.13
  '@formatjs/intl-localematcher': 0.6.1
  '@formatjs/intl-pluralrules': 5.4.6
  '@fullstory/browser': 2.0.6
  '@google/genai': 1.29.0
  '@gorhom/bottom-sheet': 5.2.6
  '@hookform/resolvers': 5.2.2
  '@lingui/babel-plugin-lingui-macro': 5.6.0
  '@lingui/cli': 5.6.0
  '@lingui/core': 5.6.0
  '@lingui/loader': 5.6.0
  '@lingui/macro': 5.6.0
  '@lingui/metro-transformer': 5.6.0
  '@lingui/react': 5.6.0
  '@lingui/swc-plugin': 5.6.0
  '@lingui/vite-plugin': 5.6.0
  '@next/eslint-plugin-next': 16.0.3
  '@orpc/client': 1.10.0
  '@orpc/contract': 1.10.0
  '@orpc/openapi': 1.10.0
  '@orpc/openapi-client': 1.10.0
  '@orpc/server': 1.10.0
  '@orpc/tanstack-query': 1.10.0
  '@posthog/ai': 7.0.0
  '@radix-ui/react-alert-dialog': 1.1.15
  '@radix-ui/react-checkbox': 1.3.3
  '@radix-ui/react-context-menu': 2.2.16
  '@radix-ui/react-dialog': 1.1.15
  '@radix-ui/react-dropdown-menu': 2.1.16
  '@radix-ui/react-label': 2.1.7
  '@radix-ui/react-popover': 1.1.15
  '@radix-ui/react-radio-group': 1.3.8
  '@radix-ui/react-slider': 1.3.6
  '@radix-ui/react-slot': 1.2.3
  '@radix-ui/react-tabs': 1.1.13
  '@radix-ui/react-toggle': 1.1.10
  '@radix-ui/react-toggle-group': 1.1.11
  '@radix-ui/react-tooltip': 1.2.8
  '@radix-ui/react-visually-hidden': 1.2.3
  '@react-email/components': 1.0.1
  '@react-email/preview-server': 5.0.4
  '@react-native-async-storage/async-storage': 2.2.0
  '@react-native-community/slider': 5.0.1
  '@react-native-google-signin/google-signin': 14.0.2
  '@react-native-masked-view/masked-view': 0.3.2
  '@react-native-menu/menu': 2.0.0
  '@react-navigation/bottom-tabs': 7.4.8
  '@react-navigation/native': 7.1.18
  '@reduxjs/toolkit': 2.9.0
  '@rn-primitives/popover': 1.2.0
  '@rn-primitives/portal': 1.3.0
  '@rn-primitives/slot': 1.2.0
  '@rn-primitives/types': 1.2.0
  '@sentry/cli': 2.55.0
  '@sentry/nextjs': 10.23.0
  '@sentry/node': 10.12.0
  '@sentry/profiling-node': 10.12.0
  '@sentry/react': 10.12.0
  '@sentry/react-native': 7.2.0
  '@sentry/vite-plugin': 3.6.1
  '@shopify/react-native-skia': 2.2.12
  '@supabase/supabase-js': 2.86.0
  '@tanstack/eslint-plugin-query': 5.91.2
  '@tanstack/react-query': 5.90.5
  '@tanstack/react-query-devtools': 5.90.2
  '@tanstack/react-router': ^1.139.14
  '@tanstack/react-table': 8.21.3
  '@tanstack/router-devtools': 1.139.14
  '@tanstack/router-plugin': 1.139.14
  '@tanstack/zod-adapter': 1.139.14
  '@testing-library/dom': 10.4.1
  '@testing-library/react': 16.3.0
  '@types/cors': 2.8.19
  '@types/express': 5.0.3
  '@types/jest': 29.5.14
  '@types/jsonwebtoken': 9.0.10
  '@types/morgan': 1.9.10
  '@types/negotiator': 0.6.4
  '@types/node': 24.7.1
  '@types/pg': 8.15.5
  '@types/qrcode': 1.5.5
  '@types/react': 19.1.10
  '@types/react-dom': 19.1.10
  '@types/react-test-renderer': 19.1.0
  '@types/supertest': 6.0.3
  '@typescript-eslint/eslint-plugin': 8.45.0
  '@typescript-eslint/parser': 8.45.0
  '@vitejs/plugin-react': 5.0.4
  ai: 5.0.93
  autoprefixer: 10.4.21
  axios: 1.12.2
  babel-plugin-macros: 3.1.0
  babel-plugin-react-compiler: 1.0.0
  babel-preset-expo: 54.0.4
  class-variance-authority: 0.7.1
  clsx: 2.1.1
  cmdk: 1.1.1
  concurrently: 9.2.1
  cors: 2.8.5
  dayjs: 1.11.18
  eslint: 9.36.0
  eslint-config-expo: 10.0.0
  eslint-config-next: 16.0.3
  eslint-config-prettier: 10.1.8
  eslint-plugin-import: 2.32.0
  eslint-plugin-lingui: 0.11.0
  eslint-plugin-prettier: 5.5.4
  eslint-plugin-react: 7.37.5
  eslint-plugin-react-compiler: 19.1.0-rc.2
  eslint-plugin-react-refresh: 0.4.22
  eslint-plugin-react-you-might-not-need-an-effect: 0.7.0
  expo: 54.0.25
  expo-apple-authentication: 8.0.7
  expo-application: 7.0.7
  expo-atlas: 0.4.3
  expo-constants: 18.0.10
  expo-dev-client: 6.0.18
  expo-device: 8.0.9
  expo-doctor: 1.17.9
  expo-font: 14.0.9
  expo-haptics: 15.0.7
  expo-linear-gradient: 15.0.7
  expo-linking: 8.0.9
  expo-localization: 17.0.7
  expo-router: 6.0.15
  expo-sharing: 14.0.7
  expo-splash-screen: 31.0.11
  expo-symbols: 1.0.7
  expo-system-ui: 6.0.8
  expo-updates: 29.0.13
  express: 5.1.0
  express-rate-limit: 8.1.0
  file-type: 21.0.0
  form-data: 4.0.4
  gettext-parser: 8.0.0
  helmet: 8.1.0
  import-in-the-middle: 1.15.0
  jest: 29.7.0
  jest-expo: 54.0.13
  jose: 6.1.2
  js-sha256: 0.11.1
  jsdom: 27.0.0
  jsonwebtoken: 9.0.2
  jwks-rsa: 3.2.0
  lucide-react: 0.544.0
  lucide-react-native: 0.545.0
  morgan: 1.10.1
  nativewind: 4.2.1
  negotiator: 1.0.0
  next: 16.0.7
  node-cache: 5.1.2
  openai: 6.7.0
  openapi-typescript: 7.9.1
  postcss: 8.5.6
  postgres: 3.4.7
  posthog-js: 1.275.1
  posthog-node: 5.11.1
  posthog-react-native: 4.9.1
  posthog-react-native-session-replay: 1.2.3
  prettier: 3.6.2
  prettier-plugin-tailwindcss: 0.6.14
  qrcode: 1.5.4
  react: 19.1.0
  react-circle-flags: 0.0.23
  react-dom: 19.1.0
  react-email: 5.0.4
  react-hook-form: 7.65.0
  react-native: 0.81.5
  react-native-css-interop: 0.2.1
  react-native-gesture-handler: 2.28.0
  react-native-ios-context-menu: 3.2.1
  react-native-ios-utilities: 5.2.0
  react-native-keyboard-controller: 1.18.5
  react-native-mmkv: 3.3.3
  react-native-play-install-referrer: 1.1.9
  react-native-purchases: 9.5.3
  react-native-purchases-ui: 9.5.3
  react-native-reanimated: 4.1.3
  react-native-safe-area-context: 5.6.1
  react-native-screens: 4.16.0
  react-native-svg: 15.12.1
  react-native-svg-circle-country-flags: 0.2.2
  react-native-url-polyfill: 2.0.0
  react-native-worklets: 0.5.1
  react-router-dom: 7.9.3
  require-in-the-middle: 7.5.2
  resend: 6.1.0
  sonner: 2.0.7
  sonner-native: 0.21.1
  stripe: 19.1.0
  supertest: 7.1.4
  tailwind-merge: 3.0.2
  tailwindcss: 3.4.17
  tailwindcss-animate: 1.0.7
  tsc-alias: 1.8.16
  tsx: 4.20.6
  turbo: 2.6.3
  typescript: 5.9.2
  typescript-eslint: 8.45.0
  uuid: 13.0.0
  victory-native: 41.20.1
  vite: 7.1.12
  vite-bundle-visualizer: 1.2.1
  vite-tsconfig-paths: 5.1.4
  vitest: 4.0.6
  webpack: 5.102.1
  zeego: 3.0.6
  zod: 4.1.12
  zustand: 5.0.8

catalogMode: prefer

catalogs:
  react19_2:
    '@types/react': 19.2.2
    '@types/react-dom': 19.2.2
    react: 19.2.0
    react-dom: 19.2.0

onlyBuiltDependencies:
  - '@sentry-internal/node-cpu-profiler'
  - '@sentry/cli'
  - '@swc/core'
  - core-js
  - esbuild
  - sharp
  - unrs-resolver
