import { ListRenderItemInfo, Pressable, Text, View } from 'react-native'
import { BottomSheetFlatList } from '@gorhom/bottom-sheet'
import { useBottomSheetPadding } from '@/hooks/use-bottom-sheet-padding'
import {
  DialectCode,
  LANGUAGES_TO_DIALECT_MAP,
  SupportedStudyLanguage,
} from '@template-app/core/constants/lang-codes'
import { Check } from 'lucide-react-native'
import { CustomCircularFlag } from '@/components/ui/custom-circular-flag'
import { useLingui } from '@lingui/react/macro'
import { dialectNameMessages } from '@template-app/i18n/lang-code-translation-utils'

export type DialectSelectorSheetContentProps = {
  close: () => void
  onDialectSelect?: (dialect: DialectCode) => void
  initialDialect?: DialectCode
  studyLanguage: SupportedStudyLanguage
}

export const DialectSettingsSelectorSheetContent = ({
  close,
  onDialectSelect,
  initialDialect,
  studyLanguage,
}: DialectSelectorSheetContentProps) => {
  const { t, i18n } = useLingui()

  const bottomSheetPadding = useBottomSheetPadding()
  const dialects: DialectCode[] = LANGUAGES_TO_DIALECT_MAP[studyLanguage]

  const handleDialectSelect = (dialect: DialectCode) => {
    onDialectSelect?.(dialect)
    close()
  }

  return (
    <View className='flex-1 px-6 pt-4' style={{ paddingBottom: bottomSheetPadding }}>
      <Text className='mb-2 text-center text-2xl font-semibold'>{t`Choose your preferred accent`}</Text>
      <>
        <Text className='mb-2 text-center text-gray-500'>{t`This will be the accent used in the audio generated by the app.`}</Text>
        <BottomSheetFlatList
          data={dialects}
          keyExtractor={(item: DialectCode) => item}
          className='flex-1'
          contentContainerStyle={{ paddingBottom: 16 }}
          renderItem={({ item }: ListRenderItemInfo<DialectCode>) => (
            <Pressable
              onPress={() => handleDialectSelect(item)}
              className='flex-row items-center justify-between border-b border-gray-100 py-4'
              android_ripple={{ color: 'rgba(0, 0, 0, 0.1)' }}
            >
              {({ pressed }) => {
                return (
                  <View
                    style={{ opacity: pressed ? 0.5 : 1 }}
                    className='flex-1 flex-row items-center justify-between px-4'
                  >
                    <View className='flex flex-row items-center gap-4'>
                      <View className='flex h-7 w-7 items-center justify-center'>
                        <CustomCircularFlag languageOrDialectCode={item} size={24} />
                      </View>
                      <Text className='text-base'>{i18n._(dialectNameMessages[item as DialectCode])}</Text>
                    </View>
                    {initialDialect === item && <Check size={20} color='#4f46e5' />}
                  </View>
                )
              }}
            </Pressable>
          )}
        />
      </>
    </View>
  )
}
