// these codes are returned from our backend, meaning they're public
// most of the time we return them to the user if our backend had an unexpected error (500), the user should not know
// what they mean because of potential security threats (hackers should now what a given 500 code means). On the other hand
// when the debugging, these codes are quite useful for YBA devs
// each of these codes should be used only once in the entire YBA codebase
export const CrypticCodeConstants = {
  PRONUNCIATION_GENERATE_TEXT_FAILED: '1000',
  PRONUNCIATION_CREATE_EXERCISE_FAILED: '1010',
  PRONUNCIATION_GENERATE_UNEXPECTED_ERROR: '1020',
  PRONUNCIATION_RETRIEVE_EXERCISES_FAILED: '1030',
  PRONUNCIATION_EXERCISE_NOT_FOUND_OR_UNAUTHORIZED: '1040',
  PRONUNCIATION_TRANSCRIPTION_FAILED: '1050',
  PRONUNCIATION_COMPLETE_UNEXPECTED_ERROR: '1060',
  PRONUNCIATION_RETRIEVE_UNEXPECTED_ERROR: '1070',
  PRONUNCIATION_RETRIEVE_SINGLE_UNEXPECTED_ERROR: '1080',
  PRONUNCIATION_RETRIEVE_HISTORY_QUERY_FAILED: '1090',
  PRONUNCIATION_RETRIEVE_HISTORY_UNEXPECTED_ERROR: '1100',

  REMOVAL_VOICE_NOT_INITIATED: '2000',
  REMOVAL_VOICE_ELEVENLABS_DELETE_FAILED: '2010',
  REMOVAL_VOICE_DB_UPDATE_FAILED: '2020',
  REMOVAL_ACCOUNT_NOT_INITIATED: '2030',
  REMOVAL_ACCOUNT_STRIPE_CANCEL_FAILED: '2040',
  REMOVAL_ACCOUNT_ELEVENLABS_DELETE_FAILED: '2050',
  REMOVAL_ACCOUNT_CUSTOMERIO_DESTROY_FAILED: '2060',
  REMOVAL_ACCOUNT_AUTH_USERS_DELETE_FAILED: '2070',
  REMOVAL_UPDATE_SUCCESS_FAILED: '2080',

  // Frequency List Exercise Errors (3000-3099)
  FREQUENCY_LIST_TEXT_GENERATION_FAILED: '3000',
  FREQUENCY_LIST_SAVED_WORDS_QUERY_FAILED: '3010',

  // Translation Exercise Errors (4000-4099)
  TRANSLATION_NO_EXERCISE_AFTER_GENERATION: '4000',
  TRANSLATION_FAILED_TO_COMPLETE_EXERCISE: '4010',
  TRANSLATION_FAILED_TO_GENERATE_EXERCISES: '4020',
  TRANSLATION_FAILED_TO_SAVE_EXERCISES: '4030',
  TRANSLATION_FAILED_TO_ANALYZE_GRAMMAR_PATTERNS: '4040',
  TRANSLATION_RETRIEVE_SINGLE_UNEXPECTED_ERROR: '4050',
  TRANSLATION_RETRIEVE_HISTORY_QUERY_FAILED: '4060',
  TRANSLATION_RETRIEVE_HISTORY_UNEXPECTED_ERROR: '4070',
}
