/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TopSecretAdminSettingsRouteImport } from './routes/top-secret-admin-settings'
import { Route as FromLandingRouteImport } from './routes/from-landing'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AccountRemovedRouteImport } from './routes/account/removed'
import { Route as ProtectedPremiumRouteImport } from './routes/_protected/_premium'
import { Route as LoginEmailIndexRouteImport } from './routes/login/email/index'
import { Route as ProtectedPricingIndexRouteImport } from './routes/_protected/pricing/index'
import { Route as LoginEmailVerifyRouteImport } from './routes/login/email/verify'
import { Route as LoginEmailSentRouteImport } from './routes/login/email/sent'
import { Route as ProtectedRedirectToCheckOutPlanIntervalRouteImport } from './routes/_protected/redirect-to-check-out/$planInterval'
import { Route as ProtectedPricingFreeTrialRouteImport } from './routes/_protected/pricing/free-trial'
import { Route as ProtectedPremiumDashboardRouteImport } from './routes/_protected/_premium/dashboard'

const TopSecretAdminSettingsRoute = TopSecretAdminSettingsRouteImport.update({
  id: '/top-secret-admin-settings',
  path: '/top-secret-admin-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const FromLandingRoute = FromLandingRouteImport.update({
  id: '/from-landing',
  path: '/from-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRemovedRoute = AccountRemovedRouteImport.update({
  id: '/account/removed',
  path: '/account/removed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPremiumRoute = ProtectedPremiumRouteImport.update({
  id: '/_premium',
  getParentRoute: () => ProtectedRoute,
} as any)
const LoginEmailIndexRoute = LoginEmailIndexRouteImport.update({
  id: '/login/email/',
  path: '/login/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPricingIndexRoute = ProtectedPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => ProtectedRoute,
} as any)
const LoginEmailVerifyRoute = LoginEmailVerifyRouteImport.update({
  id: '/login/email/verify',
  path: '/login/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailSentRoute = LoginEmailSentRouteImport.update({
  id: '/login/email/sent',
  path: '/login/email/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRedirectToCheckOutPlanIntervalRoute =
  ProtectedRedirectToCheckOutPlanIntervalRouteImport.update({
    id: '/redirect-to-check-out/$planInterval',
    path: '/redirect-to-check-out/$planInterval',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPricingFreeTrialRoute =
  ProtectedPricingFreeTrialRouteImport.update({
    id: '/pricing/free-trial',
    path: '/pricing/free-trial',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPremiumDashboardRoute =
  ProtectedPremiumDashboardRouteImport.update({
    id: '/dashboard',
    path: '/dashboard',
    getParentRoute: () => ProtectedPremiumRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/from-landing': typeof FromLandingRoute
  '/top-secret-admin-settings': typeof TopSecretAdminSettingsRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof ProtectedPremiumDashboardRoute
  '/pricing/free-trial': typeof ProtectedPricingFreeTrialRoute
  '/redirect-to-check-out/$planInterval': typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing': typeof ProtectedPricingIndexRoute
  '/login/email': typeof LoginEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/from-landing': typeof FromLandingRoute
  '/top-secret-admin-settings': typeof TopSecretAdminSettingsRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof ProtectedPremiumDashboardRoute
  '/pricing/free-trial': typeof ProtectedPricingFreeTrialRoute
  '/redirect-to-check-out/$planInterval': typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing': typeof ProtectedPricingIndexRoute
  '/login/email': typeof LoginEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/checkout-success': typeof CheckoutSuccessRoute
  '/from-landing': typeof FromLandingRoute
  '/top-secret-admin-settings': typeof TopSecretAdminSettingsRoute
  '/_protected/_premium': typeof ProtectedPremiumRouteWithChildren
  '/account/removed': typeof AccountRemovedRoute
  '/login/': typeof LoginIndexRoute
  '/_protected/_premium/dashboard': typeof ProtectedPremiumDashboardRoute
  '/_protected/pricing/free-trial': typeof ProtectedPricingFreeTrialRoute
  '/_protected/redirect-to-check-out/$planInterval': typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/_protected/pricing/': typeof ProtectedPricingIndexRoute
  '/login/email/': typeof LoginEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout-success'
    | '/from-landing'
    | '/top-secret-admin-settings'
    | '/account/removed'
    | '/login'
    | '/dashboard'
    | '/pricing/free-trial'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing'
    | '/login/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout-success'
    | '/from-landing'
    | '/top-secret-admin-settings'
    | '/account/removed'
    | '/login'
    | '/dashboard'
    | '/pricing/free-trial'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing'
    | '/login/email'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/checkout-success'
    | '/from-landing'
    | '/top-secret-admin-settings'
    | '/_protected/_premium'
    | '/account/removed'
    | '/login/'
    | '/_protected/_premium/dashboard'
    | '/_protected/pricing/free-trial'
    | '/_protected/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/_protected/pricing/'
    | '/login/email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  FromLandingRoute: typeof FromLandingRoute
  TopSecretAdminSettingsRoute: typeof TopSecretAdminSettingsRoute
  AccountRemovedRoute: typeof AccountRemovedRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginEmailSentRoute: typeof LoginEmailSentRoute
  LoginEmailVerifyRoute: typeof LoginEmailVerifyRoute
  LoginEmailIndexRoute: typeof LoginEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/top-secret-admin-settings': {
      id: '/top-secret-admin-settings'
      path: '/top-secret-admin-settings'
      fullPath: '/top-secret-admin-settings'
      preLoaderRoute: typeof TopSecretAdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/from-landing': {
      id: '/from-landing'
      path: '/from-landing'
      fullPath: '/from-landing'
      preLoaderRoute: typeof FromLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/removed': {
      id: '/account/removed'
      path: '/account/removed'
      fullPath: '/account/removed'
      preLoaderRoute: typeof AccountRemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/_premium': {
      id: '/_protected/_premium'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedPremiumRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/login/email/': {
      id: '/login/email/'
      path: '/login/email'
      fullPath: '/login/email'
      preLoaderRoute: typeof LoginEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/pricing/': {
      id: '/_protected/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ProtectedPricingIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/login/email/verify': {
      id: '/login/email/verify'
      path: '/login/email/verify'
      fullPath: '/login/email/verify'
      preLoaderRoute: typeof LoginEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/email/sent': {
      id: '/login/email/sent'
      path: '/login/email/sent'
      fullPath: '/login/email/sent'
      preLoaderRoute: typeof LoginEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/redirect-to-check-out/$planInterval': {
      id: '/_protected/redirect-to-check-out/$planInterval'
      path: '/redirect-to-check-out/$planInterval'
      fullPath: '/redirect-to-check-out/$planInterval'
      preLoaderRoute: typeof ProtectedRedirectToCheckOutPlanIntervalRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pricing/free-trial': {
      id: '/_protected/pricing/free-trial'
      path: '/pricing/free-trial'
      fullPath: '/pricing/free-trial'
      preLoaderRoute: typeof ProtectedPricingFreeTrialRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_premium/dashboard': {
      id: '/_protected/_premium/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedPremiumDashboardRouteImport
      parentRoute: typeof ProtectedPremiumRoute
    }
  }
}

interface ProtectedPremiumRouteChildren {
  ProtectedPremiumDashboardRoute: typeof ProtectedPremiumDashboardRoute
}

const ProtectedPremiumRouteChildren: ProtectedPremiumRouteChildren = {
  ProtectedPremiumDashboardRoute: ProtectedPremiumDashboardRoute,
}

const ProtectedPremiumRouteWithChildren =
  ProtectedPremiumRoute._addFileChildren(ProtectedPremiumRouteChildren)

interface ProtectedRouteChildren {
  ProtectedPremiumRoute: typeof ProtectedPremiumRouteWithChildren
  ProtectedPricingFreeTrialRoute: typeof ProtectedPricingFreeTrialRoute
  ProtectedRedirectToCheckOutPlanIntervalRoute: typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  ProtectedPricingIndexRoute: typeof ProtectedPricingIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPremiumRoute: ProtectedPremiumRouteWithChildren,
  ProtectedPricingFreeTrialRoute: ProtectedPricingFreeTrialRoute,
  ProtectedRedirectToCheckOutPlanIntervalRoute:
    ProtectedRedirectToCheckOutPlanIntervalRoute,
  ProtectedPricingIndexRoute: ProtectedPricingIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  FromLandingRoute: FromLandingRoute,
  TopSecretAdminSettingsRoute: TopSecretAdminSettingsRoute,
  AccountRemovedRoute: AccountRemovedRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginEmailSentRoute: LoginEmailSentRoute,
  LoginEmailVerifyRoute: LoginEmailVerifyRoute,
  LoginEmailIndexRoute: LoginEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
