/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as FromLandingRouteImport } from './routes/from-landing'
import { Route as ProtectedRouteImport } from './routes/_protected'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as AccountRemovedRouteImport } from './routes/account/removed'
import { Route as ProtectedPremiumDemoRouteImport } from './routes/_protected/premium-demo'
import { Route as ProtectedAdminSettingsRouteImport } from './routes/_protected/admin-settings'
import { Route as ProtectedTabsRouteImport } from './routes/_protected/_tabs'
import { Route as LoginEmailIndexRouteImport } from './routes/login/email/index'
import { Route as ProtectedPricingIndexRouteImport } from './routes/_protected/pricing/index'
import { Route as LoginEmailVerifyRouteImport } from './routes/login/email/verify'
import { Route as LoginEmailSentRouteImport } from './routes/login/email/sent'
import { Route as ProtectedRedirectToCheckOutPlanIntervalRouteImport } from './routes/_protected/redirect-to-check-out/$planInterval'
import { Route as ProtectedPricingFreeTrialRouteImport } from './routes/_protected/pricing/free-trial'
import { Route as ProtectedPricingCheckoutSuccessRouteImport } from './routes/_protected/pricing/checkout-success'
import { Route as ProtectedTabsProfileRouteImport } from './routes/_protected/_tabs/profile'
import { Route as ProtectedTabsHomeRouteImport } from './routes/_protected/_tabs/home'
import { Route as ProtectedTabsDashboardRouteImport } from './routes/_protected/_tabs/dashboard'

const FromLandingRoute = FromLandingRouteImport.update({
  id: '/from-landing',
  path: '/from-landing',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRoute = ProtectedRouteImport.update({
  id: '/_protected',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRemovedRoute = AccountRemovedRouteImport.update({
  id: '/account/removed',
  path: '/account/removed',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPremiumDemoRoute = ProtectedPremiumDemoRouteImport.update({
  id: '/premium-demo',
  path: '/premium-demo',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedAdminSettingsRoute = ProtectedAdminSettingsRouteImport.update({
  id: '/admin-settings',
  path: '/admin-settings',
  getParentRoute: () => ProtectedRoute,
} as any)
const ProtectedTabsRoute = ProtectedTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => ProtectedRoute,
} as any)
const LoginEmailIndexRoute = LoginEmailIndexRouteImport.update({
  id: '/login/email/',
  path: '/login/email/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedPricingIndexRoute = ProtectedPricingIndexRouteImport.update({
  id: '/pricing/',
  path: '/pricing/',
  getParentRoute: () => ProtectedRoute,
} as any)
const LoginEmailVerifyRoute = LoginEmailVerifyRouteImport.update({
  id: '/login/email/verify',
  path: '/login/email/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginEmailSentRoute = LoginEmailSentRouteImport.update({
  id: '/login/email/sent',
  path: '/login/email/sent',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedRedirectToCheckOutPlanIntervalRoute =
  ProtectedRedirectToCheckOutPlanIntervalRouteImport.update({
    id: '/redirect-to-check-out/$planInterval',
    path: '/redirect-to-check-out/$planInterval',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPricingFreeTrialRoute =
  ProtectedPricingFreeTrialRouteImport.update({
    id: '/pricing/free-trial',
    path: '/pricing/free-trial',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedPricingCheckoutSuccessRoute =
  ProtectedPricingCheckoutSuccessRouteImport.update({
    id: '/pricing/checkout-success',
    path: '/pricing/checkout-success',
    getParentRoute: () => ProtectedRoute,
  } as any)
const ProtectedTabsProfileRoute = ProtectedTabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedTabsRoute,
} as any)
const ProtectedTabsHomeRoute = ProtectedTabsHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => ProtectedTabsRoute,
} as any)
const ProtectedTabsDashboardRoute = ProtectedTabsDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ProtectedTabsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/from-landing': typeof FromLandingRoute
  '/admin-settings': typeof ProtectedAdminSettingsRoute
  '/premium-demo': typeof ProtectedPremiumDemoRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof ProtectedTabsDashboardRoute
  '/home': typeof ProtectedTabsHomeRoute
  '/profile': typeof ProtectedTabsProfileRoute
  '/pricing/checkout-success': typeof ProtectedPricingCheckoutSuccessRoute
  '/pricing/free-trial': typeof ProtectedPricingFreeTrialRoute
  '/redirect-to-check-out/$planInterval': typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing': typeof ProtectedPricingIndexRoute
  '/login/email': typeof LoginEmailIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/from-landing': typeof FromLandingRoute
  '/admin-settings': typeof ProtectedAdminSettingsRoute
  '/premium-demo': typeof ProtectedPremiumDemoRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login': typeof LoginIndexRoute
  '/dashboard': typeof ProtectedTabsDashboardRoute
  '/home': typeof ProtectedTabsHomeRoute
  '/profile': typeof ProtectedTabsProfileRoute
  '/pricing/checkout-success': typeof ProtectedPricingCheckoutSuccessRoute
  '/pricing/free-trial': typeof ProtectedPricingFreeTrialRoute
  '/redirect-to-check-out/$planInterval': typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/pricing': typeof ProtectedPricingIndexRoute
  '/login/email': typeof LoginEmailIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/from-landing': typeof FromLandingRoute
  '/_protected/_tabs': typeof ProtectedTabsRouteWithChildren
  '/_protected/admin-settings': typeof ProtectedAdminSettingsRoute
  '/_protected/premium-demo': typeof ProtectedPremiumDemoRoute
  '/account/removed': typeof AccountRemovedRoute
  '/login/': typeof LoginIndexRoute
  '/_protected/_tabs/dashboard': typeof ProtectedTabsDashboardRoute
  '/_protected/_tabs/home': typeof ProtectedTabsHomeRoute
  '/_protected/_tabs/profile': typeof ProtectedTabsProfileRoute
  '/_protected/pricing/checkout-success': typeof ProtectedPricingCheckoutSuccessRoute
  '/_protected/pricing/free-trial': typeof ProtectedPricingFreeTrialRoute
  '/_protected/redirect-to-check-out/$planInterval': typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  '/login/email/sent': typeof LoginEmailSentRoute
  '/login/email/verify': typeof LoginEmailVerifyRoute
  '/_protected/pricing/': typeof ProtectedPricingIndexRoute
  '/login/email/': typeof LoginEmailIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/from-landing'
    | '/admin-settings'
    | '/premium-demo'
    | '/account/removed'
    | '/login'
    | '/dashboard'
    | '/home'
    | '/profile'
    | '/pricing/checkout-success'
    | '/pricing/free-trial'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing'
    | '/login/email'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/from-landing'
    | '/admin-settings'
    | '/premium-demo'
    | '/account/removed'
    | '/login'
    | '/dashboard'
    | '/home'
    | '/profile'
    | '/pricing/checkout-success'
    | '/pricing/free-trial'
    | '/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/pricing'
    | '/login/email'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/from-landing'
    | '/_protected/_tabs'
    | '/_protected/admin-settings'
    | '/_protected/premium-demo'
    | '/account/removed'
    | '/login/'
    | '/_protected/_tabs/dashboard'
    | '/_protected/_tabs/home'
    | '/_protected/_tabs/profile'
    | '/_protected/pricing/checkout-success'
    | '/_protected/pricing/free-trial'
    | '/_protected/redirect-to-check-out/$planInterval'
    | '/login/email/sent'
    | '/login/email/verify'
    | '/_protected/pricing/'
    | '/login/email/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedRoute: typeof ProtectedRouteWithChildren
  FromLandingRoute: typeof FromLandingRoute
  AccountRemovedRoute: typeof AccountRemovedRoute
  LoginIndexRoute: typeof LoginIndexRoute
  LoginEmailSentRoute: typeof LoginEmailSentRoute
  LoginEmailVerifyRoute: typeof LoginEmailVerifyRoute
  LoginEmailIndexRoute: typeof LoginEmailIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/from-landing': {
      id: '/from-landing'
      path: '/from-landing'
      fullPath: '/from-landing'
      preLoaderRoute: typeof FromLandingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/removed': {
      id: '/account/removed'
      path: '/account/removed'
      fullPath: '/account/removed'
      preLoaderRoute: typeof AccountRemovedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/premium-demo': {
      id: '/_protected/premium-demo'
      path: '/premium-demo'
      fullPath: '/premium-demo'
      preLoaderRoute: typeof ProtectedPremiumDemoRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/admin-settings': {
      id: '/_protected/admin-settings'
      path: '/admin-settings'
      fullPath: '/admin-settings'
      preLoaderRoute: typeof ProtectedAdminSettingsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_tabs': {
      id: '/_protected/_tabs'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedTabsRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/login/email/': {
      id: '/login/email/'
      path: '/login/email'
      fullPath: '/login/email'
      preLoaderRoute: typeof LoginEmailIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/pricing/': {
      id: '/_protected/pricing/'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof ProtectedPricingIndexRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/login/email/verify': {
      id: '/login/email/verify'
      path: '/login/email/verify'
      fullPath: '/login/email/verify'
      preLoaderRoute: typeof LoginEmailVerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/email/sent': {
      id: '/login/email/sent'
      path: '/login/email/sent'
      fullPath: '/login/email/sent'
      preLoaderRoute: typeof LoginEmailSentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protected/redirect-to-check-out/$planInterval': {
      id: '/_protected/redirect-to-check-out/$planInterval'
      path: '/redirect-to-check-out/$planInterval'
      fullPath: '/redirect-to-check-out/$planInterval'
      preLoaderRoute: typeof ProtectedRedirectToCheckOutPlanIntervalRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pricing/free-trial': {
      id: '/_protected/pricing/free-trial'
      path: '/pricing/free-trial'
      fullPath: '/pricing/free-trial'
      preLoaderRoute: typeof ProtectedPricingFreeTrialRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/pricing/checkout-success': {
      id: '/_protected/pricing/checkout-success'
      path: '/pricing/checkout-success'
      fullPath: '/pricing/checkout-success'
      preLoaderRoute: typeof ProtectedPricingCheckoutSuccessRouteImport
      parentRoute: typeof ProtectedRoute
    }
    '/_protected/_tabs/profile': {
      id: '/_protected/_tabs/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedTabsProfileRouteImport
      parentRoute: typeof ProtectedTabsRoute
    }
    '/_protected/_tabs/home': {
      id: '/_protected/_tabs/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof ProtectedTabsHomeRouteImport
      parentRoute: typeof ProtectedTabsRoute
    }
    '/_protected/_tabs/dashboard': {
      id: '/_protected/_tabs/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedTabsDashboardRouteImport
      parentRoute: typeof ProtectedTabsRoute
    }
  }
}

interface ProtectedTabsRouteChildren {
  ProtectedTabsDashboardRoute: typeof ProtectedTabsDashboardRoute
  ProtectedTabsHomeRoute: typeof ProtectedTabsHomeRoute
  ProtectedTabsProfileRoute: typeof ProtectedTabsProfileRoute
}

const ProtectedTabsRouteChildren: ProtectedTabsRouteChildren = {
  ProtectedTabsDashboardRoute: ProtectedTabsDashboardRoute,
  ProtectedTabsHomeRoute: ProtectedTabsHomeRoute,
  ProtectedTabsProfileRoute: ProtectedTabsProfileRoute,
}

const ProtectedTabsRouteWithChildren = ProtectedTabsRoute._addFileChildren(
  ProtectedTabsRouteChildren,
)

interface ProtectedRouteChildren {
  ProtectedTabsRoute: typeof ProtectedTabsRouteWithChildren
  ProtectedAdminSettingsRoute: typeof ProtectedAdminSettingsRoute
  ProtectedPremiumDemoRoute: typeof ProtectedPremiumDemoRoute
  ProtectedPricingCheckoutSuccessRoute: typeof ProtectedPricingCheckoutSuccessRoute
  ProtectedPricingFreeTrialRoute: typeof ProtectedPricingFreeTrialRoute
  ProtectedRedirectToCheckOutPlanIntervalRoute: typeof ProtectedRedirectToCheckOutPlanIntervalRoute
  ProtectedPricingIndexRoute: typeof ProtectedPricingIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedTabsRoute: ProtectedTabsRouteWithChildren,
  ProtectedAdminSettingsRoute: ProtectedAdminSettingsRoute,
  ProtectedPremiumDemoRoute: ProtectedPremiumDemoRoute,
  ProtectedPricingCheckoutSuccessRoute: ProtectedPricingCheckoutSuccessRoute,
  ProtectedPricingFreeTrialRoute: ProtectedPricingFreeTrialRoute,
  ProtectedRedirectToCheckOutPlanIntervalRoute:
    ProtectedRedirectToCheckOutPlanIntervalRoute,
  ProtectedPricingIndexRoute: ProtectedPricingIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedRoute: ProtectedRouteWithChildren,
  FromLandingRoute: FromLandingRoute,
  AccountRemovedRoute: AccountRemovedRoute,
  LoginIndexRoute: LoginIndexRoute,
  LoginEmailSentRoute: LoginEmailSentRoute,
  LoginEmailVerifyRoute: LoginEmailVerifyRoute,
  LoginEmailIndexRoute: LoginEmailIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
