export const NAME_OF_SECRET_HEADER_USED_FOR_AUTHENTICATING_FRONTEND = 'prev-modified-at' // made cryptic on purpose
export const ERROR_CODE_FOR_AUTHENTICATING_FRONTEND = '10'
export const ERROR_CODE_FOR_INVALID_TOKEN = '30'
export const ERROR_CODE_FOR_SUBSCRIPTION_REQUIRED = 'SUBSCRIPTION_REQUIRED'